#!/bin/bash

set -e

fname="${5} - ${2}.ogg"
fname="${fname//\//-}"

curl -s ${4//'\n'/' '} > cover.jpeg
./ogg-image-blobber cover.jpeg

cat > "${fname}"
{
	echo "SPOTIFY_ID=${1}"
	echo "TITLE=${2//'\n'/' '}"
	echo "ALBUM=${3//'\n'/' '}"
	echo "METADATA_BLOCK_PICTURE=$(cat cover.base64)"
	shift 4
	for artist in "$@"; do
		echo "ARTIST=${artist//'\n'/' '}"
	done
} | vorbiscomment -a "${fname}"
echo "${fname}"

rm -f cover.jpeg
rm -f cover.base64
